services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: projet_solarx
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    command: --log-bin-trust-function-creators=1
    ports:
      - "3306:3306"
    volumes:
      - ./projet_solarx.sql:/docker-entrypoint-initdb.d/projet_solarx.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"

  python_app:
    image: python:3.10
    container_name: python_env
    restart: always
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: ["tail", "-f", "/dev/null"]